# Generated by Django 5.1.1 on 2024-10-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
