# Generated by Django 5.1.1 on 2025-01-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_otp",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_otp_sent",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verified",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
