# Generated by Django 5.1.1 on 2025-01-03 15:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0004_alter_category_options_remove_userprofile_email_otp_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="menu_item",
        ),
        migrations.RemoveField(
            model_name="order",
            name="price_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("HALF", "Half"), ("FULL", "Full")],
                        default="FULL",
                        max_length=8,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
