# Generated by Django 5.1.1 on 2025-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0005_remove_order_menu_item_remove_order_price_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
    ]
