# Generated by Django 5.1.1 on 2025-07-03 23:21

from django.db import migrations, models

import common.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_menuitem_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=common.storage_backends.PublicMediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=common.storage_backends.PublicMediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="qr_code",
            field=models.ImageField(
                storage=common.storage_backends.PublicMediaStorage(),
                upload_to="",
            ),
        ),
    ]
