# Generated by Django 5.1.1 on 2026-04-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_category_image_alter_menuitem_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.category",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.table"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.order"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.chain"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="qr_code",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.chain"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
