# Generated by Django 5.1.1 on 2026-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0008_alter_category_restaurant_alter_menuitem_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="menu_item",
        ),
        migrations.RemoveField(
            model_name="order",
            name="table",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="table",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Chain",
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
        migrations.DeleteModel(
            name="Table",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
